#!/bin/bash
wget https://ip-ranges.amazonaws.com/ip-ranges.json
IPS=$(grep ip_prefix ip-ranges.json  | grep -Eo ': "[^"]+' | grep -Eo '[0-9\./]+')
for i in $IPS
do
iptables -A INPUT -s $i -j DROP
done
